if (!window.ActiveXObject){ document.write("<div style=\"text-align: center; margin: 0px auto; width:160px; height:600px; position:relative;\">"); } var prot = 'http:'; var patternUrl = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;  var psa = 0; var resultApproved = null; var resultServing = null; var approvedURLs = ['hijinksensue.com']; var adServingURLs = ['madadsmedia.com','ads-by.madadsmedia.com'];  var store = "0"; var resultBlocked = null; var blockedURLs = ["-live.com","porn","fuck","xxx","tits","pussy","xrated","cunt","gangbang","blowjob","jailbait"]; var googlePage = 'www.hijinksensue.com'; var SiteID='6612';  var realURL = 1; var iframe = 0; var url = 0; var src = 0;  if (top === self){ var refURL = document.location.href; url = encodeURIComponent(document.location.href); src = 0; } else { var refURL = document.referrer; url = encodeURIComponent(document.location.href); src = encodeURIComponent(document.referrer); } if(typeof setMIframe !== 'undefined'){ iframe = setMIframe; } if(typeof setMRefURL !== 'undefined'){ refURL = setMRefURL; if(iframe == 1){ src = setMRefURL; }else{ url = setMRefURL; } }  if(!refURL){ refURL = googlePage ? prot+'//'+googlePage : document.location.href; realURL = 0; }  if(iframe == 1 && !src){ refURL = document.location.href; src = 'BlankRefServe'; realURL = 0; }  var pb160x600='58/6612/default/160x600.js';  if(patternUrl.test(refURL.toLowerCase())){ for(var i = 0; i < blockedURLs.length; i++){ if(refURL.toLowerCase().match(blockedURLs[i])){ resultBlocked = true; break; }} if(!resultBlocked){ for(var i = 0; i < approvedURLs.length; i++){ if(refURL.toLowerCase().match(approvedURLs[i])) { resultApproved = true; break; }} for(var i = 0; i < adServingURLs.length; i++){ if(refURL.toLowerCase().match(adServingURLs[i])){ resultServing = adServingURLs[i]; break; }}  if(resultApproved || resultServing){ document.write("<img src='http://pixel.madadsmedia.com/?site=6612&size=3&iframe="+iframe+"&url="+url+"&src="+src+"&store="+store+"' style='display:none'>"); document.write("<script type='text/javascript'>");var rp_account='8223';var rp_site='14911';var rp_zonesize='121224-9';var rp_adtype='js';var rp_smartfile='[SMART FILE URL]';var rp_kw='Hijinksensue.com'; var rp_inventory = {Site : "Hijinksensue.com"}; var SizeID='3';document.write("<\/script>");document.write("<script type='text/javascript' src='http://ads.rubiconproject.com/ad/8223.js'>");document.write("<\/script>"); var _qevents = _qevents || [];
                                                  (function() {
                                                  var elem = document.createElement('script');
                                                  elem.src = (document.location.protocol == 'https:' ? 'https://secure' : 'http://edge') + '.quantserve.com/quant.js';
                                                  elem.async = true;
                                                  elem.type = 'text/javascript';
                                                  var scpt = document.getElementsByTagName('script')[0];
                                                  scpt.parentNode.insertBefore(elem, scpt);
                                                  })();
                                                  _qevents.push({
                                                  qacct:'p-QAjpCznqPvtcy'
                                                  }); } else { psa = '1'; var dw = document; if(typeof pb160x600 != 'undefined'){ dw.write('<script language="JavaScript" type="text/javascript"'); dw.write('src="http://ads-by.madadsmedia.com/tags/' + pb160x600 + '">'); dw.write('<\/scr' + 'ipt>'); } else { dw.write('<script language="JavaScript" type="text/javascript"'); dw.write('src="http://ads-by.madadsmedia.com/tags/58/6612/default/160x600.js">'); dw.write('<\/scr' + 'ipt>'); } }} else { document.write('<img src="'+prot+'\//pixel.madadsmedia.com/?site=6612&size=3&iframe='+iframe+'&url='+url+'&src='+src+'&blocked=1" style="display:none">'); } } if (!window.ActiveXObject){ document.write("<\/div>"); }