window.pp.Ad=function(a){this.options=a;this.FrameStatus={JS:0,IFRAME:1,IFRAME_BREAKOUT:2,DOUBLE_IFRAME:3};this.errorStep=""};
window.pp.Ad.prototype={loopingPrefix:"cwl_",kvPrefix:"cwkv_",display:function(){try{this.setState(),this.getAd()}catch(a){-1==this.getAdUrl.indexOf("?")&&this.buildGetAdUrlFromOptions(this.options),document.write("<script language='javascript' src='"+this.getAdUrl+(-1<this.getAdUrl.indexOf("?")?"&":"?")+"jserr="+this.exMsg(a)+"&errSt="+this.errorStep+"'><\/script>")}},setState:function(){try{this.evalQueryString(),this.storage=navigator,this.getAdUrl=this.options.cu,this.isDefined(this.options.cwif)||
(this.options.cwif=!1),this.smartFileLocation=this.getSmartFileLocation(),this.frameStatus=this.getDisplayType(),this.tile=this.getTile(this.frameStatus,this.storage,this.kvPrefix),this.isOpera=this.isOpera(),this.position=this.getPosition()}catch(a){throw this.setErrorStep("setSt"),a;}},isDefined:function(a){return"undefined"!=typeof a},getAd:function(){try{var a=this;this.isInIFrame()||(this.isDefined(this.getAdUrl)?(this.attachUnloadHandler(function(){a.onUnload(a.loopingPrefix,a.kvPrefix,a.storage)}),
this.buildGetAdUrl(),this.writeAd()):document.write("Thank you, your file's location is:  "+window.location))}catch(b){throw this.setErrorStep("getAd"),b;}},getDisplayType:function(){try{return window==top?this.FrameStatus.JS:document.location.host==top.document.location.host?this.FrameStatus.IFRAME_BREAKOUT:this.FrameStatus.IFRAME}catch(a){try{if(top&&parent==top||parent.document.referrer)return this.FrameStatus.IFRAME}catch(b){}return this.FrameStatus.DOUBLE_IFRAME}},getTile:function(a,b,d){try{if(!this.isJSOrIFrameBreakout())return-1;
a=d+"tile";null==b[a]&&(b[a]=0);return++b[a]}catch(c){return-1}},isInIFrame:function(){return this.options.cwif||this.isJSOrIFrameBreakout()||!this.smartFileLocation?!1:this.breakOutFromFrames()},evalQueryString:function(){var a=location.search.slice(1);!this.isEmpty(a)&&this.strContains(a,"this.options.cwif")&&eval(unescape(a))},isEmpty:function(a){return!a||null==a||"string"==typeof a&&("null"==a||!this.isDefined(a)||""==a.replace(/\s*/,""))},breakOutFromFrames:function(){var a=this.smartFileLocation+
"?this.options.cwif=true;",b;for(b in this.options)a+=this.getKeyValueString("this.options."+b,this.options[b]);return(b=this.getBreakOutFrame(this.smartFileLocation))?(b.location.replace(a),!0):!1},getKeyValueString:function(a,b){return!this.isEmpty(b)?a+"='"+b+"';":""},getBreakOutFrame:function(a){var b=window;try{var d=a.split("//")[1].split("/")[0],c=b.location.host;if(c==d)return null;for(;b.parent.window!=b.top;){c=b.parent.location.host;if(this.strContains(c,d))break;b=b.parent.window}}catch(e){}return b},
attachUnloadHandler:function(a){try{var b=window;if(this.isDefined(b.addEventListener)&&!this.isOpera)b.addEventListener("beforeunload",a,!1);else if(this.isDefined(b.attachEvent)&&!this.isOpera)b.attachEvent("onbeforeunload",a);else{var d=b.onload;b.onload="function"!=typeof d?a:function(){d();a()}}}catch(c){throw this.setErrorStep("unload"),c;}},onUnload:function(a,b,d){try{for(var c in d)0==c.indexOf(a)&&(d[c]=0),0==c.indexOf(b)&&(d[c]=0)}catch(e){}},buildGetAdUrl:function(){this.buildGetAdUrlFromOptions(this.options);
this.getAdUrl+="&rq="+this.getLoopingCount();this.getAdUrl+="&dw="+this.getWidth();this.getAdUrl+="&cwu="+this.processUrlForQSValue(this.getUrl());this.getAdUrl+="&cwr="+this.processUrlForQSValue(this.getReferrer());this.getAdUrl+="&mrnd="+this.getRandomNumber();this.getAdUrl+="&if="+this.frameStatus;this.getAdUrl+="&tl="+this.tile;this.getAdUrl+="&pxy="+this.position;this.getAdUrl+="&cxy="+this.getClientDimensions();this.getAdUrl+="&dxy="+this.getDocumentDimensions();this.getAdUrl+="&tz="+(new Date).getTimezoneOffset();
this.getAdUrl+="&ln="+this.getLanguage()},buildGetAdUrlFromOptions:function(a){this.getAdUrl+="?tagver=1";this.getAdUrl+=this.safeQs("ca",a.ca);this.getAdUrl+=this.safeQs("cp",a.cp);this.getAdUrl+=this.safeQs("ct",a.ct);this.getAdUrl+=this.safeQs("cwod",a.cwod);this.getAdUrl+=this.safeQs("epid",a.epid);this.getAdUrl+=this.safeQs("esid",a.esid);this.getAdUrl+=this.safeQs("ifurl",a.ifurl);this.getAdUrl+=this.safeQs("tppg",this.processUrlForQSValue(a.tppg));this.getAdUrl+=this.safeQs("brk",a.brk);this.getAdUrl+=
this.safeQs("ccid",a.ccid);this.getAdUrl+=this.safeQs("wp",a.wp);this.getAdUrl+=this.safeQs("cf",this.processUrlForQSValue(a.cf));this.getAdUrl+=this.safeQs("asv",a.asv);this.getAdUrl+=this.addPubTokens(a.PPTOKEN)},addPubTokens:function(a){var b="";if(this.isDefined(a)&&null!=a)for(attr in a)b+=this.safeQs("PPTOKEN_"+attr,a[attr]);return b},safeQs:function(a,b){return this.isDefined(b)?"&"+a+"="+b:""},processUrlForQSValue:function(a){a=escape(a);a=a.replace(/\+/g,"%2B");return a=a.replace(/\//g,"%2F")},
getLoopingCount:function(){try{var a=this.loopingPrefix+this.options.ct+"_"+this.options.cf+"_"+this.options.esid+"_"+this.position;this.storage[a]?this.storage[a]++:this.storage[a]=1;return this.storage[a]}catch(b){return this.setErrorStep("loop"),1}},getWidth:function(){var a=0;try{document.body||document.write('<div id="cwViz1" style="width:0px; height:0px; display:none; visibility:hidden;">o</div>'),self.innerWidth?a=self.innerWidth:document.documentElement&&document.documentElement.clientHeight?
a=document.documentElement.clientWidth:document.body&&(a=document.body.clientWidth)}catch(b){a=-1}return a},getUrl:function(){var a="",b="",d="",c=window;try{if(this.isJSOrIFrameBreakout())return top.location}catch(e){}try{b=document.location;if(b==top.location)a=b;else for(;;){a=c.document.location;c.document.referrer&&(d=c.document.referrer);if(c==c.parent)break;else c.document.referrer&&(a=d);c=c.parent}if(""==a||null==a)a=d?d:b}catch(f){d&&""!=d?a=d:""==a&&(a=b)}return a},getReferrer:function(){try{if(this.isJSOrIFrameBreakout())return top.document.referrer}catch(a){}return""},
getPosition:function(){var a=[0,0];try{var b="cw_td_"+this.getRandomNumber();document.write('<div id="'+b+'" style="height:0;width:0;"></div>');var d=document.getElementById(b),a=this.getOffsetPosition(d);d.style.display="none";if(window!=top){var c=this.getIFramePosition();a[0]+=c[0];a[1]+=c[1]}}catch(e){}return a},getRandomNumber:function(){return Math.floor(1E8*Math.random())},getOffsetPosition:function(a){var b=[0,0];null!=a&&(a=a.getBoundingClientRect(),b=[Math.round(a.left),Math.round(a.top)]);
return b},getIFramePosition:function(){var a=this.getTopFrame();if(null==a)throw-15;try{return this.getOffsetPosition(a.frameElement)}catch(b){}for(var d=top.document.getElementsByTagName("IFRAME"),c=0;c<d.length;c++)if(d[c].contentWindow.location==a.location)return this.getOffsetPosition(d[c])},getTopFrame:function(){try{for(var a=[],b=window,d=20;0<--d;){a.push(b);if(b==top||null==b.parent)return a[a.length-2];b=b.parent}return null}catch(c){return null}},getClientDimensions:function(){try{return[window.innerWidth||
top.document.documentElement.clientWidth||top.document.body.clientWidth,window.innerHeight||top.document.documentElement.clientHeight||top.document.body.clientHeight]}catch(a){return""}},getDocumentDimensions:function(){try{return[top.window.document.body.offsetWidth,top.window.document.body.offsetHeight]}catch(a){return""}},getLanguage:function(){try{if(navigator){var a=[];navigator.language&&a.push(navigator.language);navigator.userLanguage&&a.push(navigator.userLanguage);navigator.browserLanguage&&
a.push(navigator.browserLanguage);navigator.systemLanguage&&a.push(navigator.systemLanguage);return a.join(",")}}catch(b){}return""},writeAd:function(){document.writeln('<script type="text/javascript" src="'+this.getAdUrl+'"><\/script>')},isJSOrIFrameBreakout:function(){return this.frameStatus==this.FrameStatus.JS||this.frameStatus==this.FrameStatus.IFRAME_BREAKOUT},exMsg:function(a){try{if("object"==typeof a)return this.isDefined(JSON)&&this.isDefined(JSON.stringify)?escape(JSON.stringify(a)):escape(a.toString())}catch(b){}return escape(a)},
strContains:function(a,b){return a&&b&&-1!=a.toLowerCase().indexOf(b.toLowerCase())},getSmartFileLocation:function(){try{if(this.isDefined(this.options.cwfl)&&0<this.options.cwfl.length)return this.options.cwfl;if(this.isDefined(window.cwfl))return window.cwfl}catch(a){this.setErrorStep("smartFile")}return!1},isOpera:function(){try{return this.strContains(navigator.userAgent,"opera")}catch(a){return this.setErrorStep("opera"),!1}},setErrorStep:function(a){this.errorStep+="|"+a}};
"undefined"!=typeof pp_display_ad&&"undefined"!=typeof pp_options&&(new pp.Ad(pp_options)).display();